name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: |
        chmod u+x ./build.sh
        ./build.sh

    - name: changelog
      run: sed -n "/^## \[$GITHUB_REF_NAME\]/,/^##/p" CHANGELOG.md | head -n -1 > changelog.txt

    - name: release
      run: gh release create $GITHUB_REF_NAME --notes-file changelog.txt dist/github-api.pyz
      env:
        GH_TOKEN: ${{ github.token }}
